# Generated by Django 6.0.6 on 2026-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("tenant", "barcode")},
        ),
    ]
