# Generated by Django 6.0.6 on 2026-06-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_product_barcode_alter_product_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="tenant",
            name="subscription_status",
            field=models.CharField(default="trial", max_length=20),
        ),
        migrations.AddField(
            model_name="tenant",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
