# Generated by Django 6.0.6 on 2026-06-18 22:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tenant_currency_tenant_subscription_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="month",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="year",
        ),
        migrations.AddField(
            model_name="expense",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="expense",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("RENT", "Rent"),
                    ("UTILITIES", "Utilities"),
                    ("SALARIES", "Salaries"),
                    ("LOGISTICS", "Logistics"),
                    ("MARKETING", "Marketing"),
                    ("MISC", "Miscellaneous"),
                ],
                max_length=20,
            ),
        ),
    ]
