# Generated by Django 6.0.6 on 2026-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_expense_month_remove_expense_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productunit",
            name="buying_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
