# Generated by Django 6.0.6 on 2026-06-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_productunit_buying_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="currency",
            field=models.CharField(default="UGX", max_length=10),
        ),
    ]
