# Generated by Django 6.0.6 on 2026-07-01 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_tenant_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenant",
            old_name="trial_ends_at",
            new_name="trial_end_date",
        ),
        migrations.AddField(
            model_name="tenant",
            name="current_plan",
            field=models.CharField(
                choices=[("basic", "Basic"), ("premium", "Premium")],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="trial_start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("trial", "Trial"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("suspended", "Suspended"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
    ]
